services:
  mqtt:
    image: eclipse-mosquitto:2.0.21
    container_name: ss-mqtt
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "8883:8883"
    networks:
      - ss-mqttnet
  nodered:
    container_name: ss-nodered
    build:
      context: ./Node-Red
    restart: always
    volumes:
      - nodered-data:/data
      - ./Node-Red/images:/data/images
      - ./Node-Red/certs:/certs:ro
    ports:
      - "1880:1880"
    networks:
      - ss-mqttnet

networks:
  ss-mqttnet:

volumes:
  nodered-data:
