# Use official PostgreSQL image
FROM postgres:17

# Set environment variables for DB
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=image_db

# Expose default Postgres port
EXPOSE 5432

# Use default CMD (start postgres)
