name: Push Node-RED to Dockerhub and deploy to DigitalOcean Kubernetes
on:
  push:
    branches:
      - main
    pull_request:

jobs:
  login-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_2001SLAVIC }}

      - name: Build and push Docker image
        uses: docker/build-push-action@6.17.0
        with:
          context: ./Node-Red
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}/ss-nodered:${{ github.sha }} , ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}/ss-nodered:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_2001SLAVIC }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-32-2-do-1-fra1-1748115745699

      - name: Cleanup all resources in namespace
        run: kubectl delete all,configmaps,pvc --all -n ss

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f kubernetes/deployment.yaml
