name: Push Node-RED to Dockerhub

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_2001SLAVIC }}

      - name: Build and push Docker image
        uses: docker/build-push-action@6.17.0
        with:
          context: ./Node-Red
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}/ss-nodered:${{ github.sha }} , ${{ secrets.DOCKERHUB_USERNAME_2001SLAVIC }}/ss-nodered:latest
