name: Generate SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Use the latest checkout version
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: syft dir:. --output cyclonedx-json > sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: sbom
          path: sbom.json