name: Security Scan
on:
  push:
    branches: [main]
permissions:
  contents: read
  security-events: write
  issues: write
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        path: .
        format: spdx-json
    - name: Vulnerability Scan
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: .
        fail-build: false
        severity-cutoff: high
    - name: Upload SARIF
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Create Issue
      if: steps.scan.outputs.vulnerabilities-found == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security Vulnerabilities Found',
            body: 'High/Critical vulnerabilities detected. Check Security tab.'
          })