name: Static Analysis

on:
  push:
    branches:
      - main  # Changed from "master" to match modern default branches
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest  # Better to use standard runner
    permissions:
      security-events: write  # Only needed permission for SARIF upload

    steps:
      - uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: |
          # Specific file patterns for Arduino projects
          find . -name "*.ino" -exec cppcheck --enable=all --xml --xml-version=2 {} + 2> report.xml

      - name: Convert to SARIF
        uses: Flast/cppcheck-sarif@v2
        with:
          input: report.xml
          output: report.sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif